# Generated by Django 6.0.3 on 2026-03-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "tempo_preparo",
                    models.PositiveIntegerField(
                        blank=True, help_text="Tempo em minutos", null=True
                    ),
                ),
                (
                    "ingredientes",
                    models.ManyToManyField(
                        related_name="receitas", to="receita.ingrediente"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Utilizador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "receitas_favoritas",
                    models.ManyToManyField(
                        blank=True, related_name="utilizadores", to="receita.receita"
                    ),
                ),
            ],
        ),
    ]
