# Generated by Django 6.0.4 on 2026-04-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("nivel", models.CharField(max_length=50)),
                ("evidencia", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("entidade", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=50)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("concluida", models.BooleanField(default=False)),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True, related_name="formacoes", to="portfolio.competencia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sigla", models.CharField(max_length=20)),
                ("instituicao", models.CharField(max_length=100)),
                ("duracao_anos", models.IntegerField()),
                ("ano_inicio", models.IntegerField()),
                ("plano_estudo_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="makingof/"),
                ),
                ("descricao", models.TextField()),
                ("modificacoes", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "fotografia",
                    models.ImageField(blank=True, null=True, upload_to="perfil/"),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("github", models.URLField(blank=True, null=True)),
                ("cv_pdf", models.FileField(blank=True, null=True, upload_to="cv/")),
                (
                    "licenciatura",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="projetos/"),
                ),
                ("github_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
                ("link", models.URLField(blank=True, null=True)),
                ("interesse", models.IntegerField()),
                ("tipo", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                ("resumo", models.TextField(blank=True, null=True)),
                ("interesse", models.IntegerField()),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="tfcs", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ano_curricular", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("descricao", models.TextField()),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="ucs/")),
                ("ects", models.IntegerField()),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucs",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
        migrations.AddField(
            model_name="competencia",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competencias",
                to="portfolio.perfil",
            ),
        ),
        migrations.AddField(
            model_name="projeto",
            name="competencias",
            field=models.ManyToManyField(
                blank=True, related_name="projetos", to="portfolio.competencia"
            ),
        ),
        migrations.AddField(
            model_name="projeto",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projetos",
                to="portfolio.perfil",
            ),
        ),
        migrations.AddField(
            model_name="makingof",
            name="projeto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="makingofs",
                to="portfolio.projeto",
            ),
        ),
        migrations.AddField(
            model_name="projeto",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True, related_name="projetos", to="portfolio.tecnologia"
            ),
        ),
        migrations.AddField(
            model_name="formacao",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True, related_name="formacoes", to="portfolio.tecnologia"
            ),
        ),
        migrations.AddField(
            model_name="competencia",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True, related_name="competencias", to="portfolio.tecnologia"
            ),
        ),
        migrations.AddField(
            model_name="projeto",
            name="unidade_curricular",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projetos",
                to="portfolio.unidadecurricular",
            ),
        ),
    ]
