# Generated by Django 6.0.4 on 2026-04-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0002_competencia_formacao_licenciatura_makingof_perfil_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="licenciatura",
            name="codigo",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="grau",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="unidade_organica",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="apresentacao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="bibliografia",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="codigo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="objetivos",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="programa",
            field=models.TextField(blank=True, null=True),
        ),
    ]
