# Generated by Django 6.0.4 on 2026-04-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_licenciatura_codigo_licenciatura_grau_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="makingof",
            name="projeto",
        ),
    ]
