# Generated by Django 6.0.4 on 2026-04-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_remove_makingof_projeto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="codigo",
        ),
    ]
