# Generated by Django 6.0.4 on 2026-04-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_remove_unidadecurricular_codigo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="bibliografia",
        ),
    ]
