# Generated by Django 6.0.4 on 2026-04-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_remove_unidadecurricular_bibliografia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="descricao",
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="bibliografia",
            field=models.TextField(blank=True, null=True),
        ),
    ]
