# Generated by Django 6.0.4 on 2026-04-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_remove_unidadecurricular_descricao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadecurricular",
            name="descricao",
            field=models.TextField(default="texto"),
            preserve_default=False,
        ),
    ]
